### ISSUE TITLE
cffi symbol not found in flat namespace '_ffi_prep_closure'

### ISSUE THREAD

**Issue by ricopicone** [mathworks/jupyter-matlab-proxy#25]
I can't start a MATLAB kernel in Jupyterlab or Jupyter Notebook. I started with a fresh `pyenv` Python 3.8.13. I installed Jupyterlab and Notebook and the MATLAB proxy with `pip`. When I start a notebook with the MATLAB kernel, I get the error below.

My environment:
M1 Mac
MacOS Ventura (13.1)

```
Traceback (most recent call last):
  File "/Users/ricopicone/.pyenv/versions/3.8.13/bin/matlab-proxy-app", line 5, in <module>
    from matlab_proxy.app import main
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/matlab_proxy/app.py", line 12, in <module>
    from aiohttp_session.cookie_storage import EncryptedCookieStorage
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/aiohttp_session/cookie_storage.py", line 6, in <module>
    from cryptography import fernet
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives.hmac import HMAC
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 10, in <module>
    from cryptography.hazmat.backends.openssl.hmac import _HMACContext
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 61, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/ricopicone/.pyenv/versions/3.8.13/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_prep_closure'
```

I get the same error when I click the "Open MATLAB" button in Jupyterlab.

**Comment by ricopicone** [comment]
Changing to Python 3.10.3 fixed this with Jupyterlab but not Notebook.

**Comment by prabhakk-mw** [comment]
Hi @ricopicone 

Would you please share the logs that arise out of using the notebook?

**Comment by prabhakk-mw** [comment]
Please re-open the issue if you need further assistance.
