### ISSUE TITLE
Kernel dies on Mac with M1

### ISSUE THREAD

**Issue by jonathanlilly** [mathworks/jupyter-matlab-proxy#31]
Hi, 

Running this on a Mac with an M1 chip, the Matlab kernel appears to be installed correctly but then dies immediately.  Any help would be appreciated.  

I'm running Matlab 2023a and I have tried both using micromamba or using the x86 version of miniconda.  In both cases I get this error:

Traceback (most recent call last):
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/jupyter_matlab_kernel/__main__.py", line 8, in <module>
    IPKernelApp.launch_instance(kernel_class=MATLABKernel)
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/traitlets/config/application.py", line 1042, in launch_instance
    app.initialize(argv)
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 693, in initialize
    self.init_kernel()
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 541, in init_kernel
    kernel = kernel_factory(
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/traitlets/config/configurable.py", line 551, in instance
    inst = cls(*args, **kwargs)
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/jupyter_matlab_kernel/kernel.py", line 145, in __init__
    ) = mwi_comm_helpers.fetch_matlab_proxy_status(self.murl, self.headers)
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/jupyter_matlab_kernel/mwi_comm_helpers.py", line 36, in fetch_matlab_proxy_status
    data = resp.json()
  File "/Users/lilly/miniconda3/envs/jlab/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[W 2023-05-08 00:31:00.074 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2023-05-08 00:31:00.075 ServerApp] Kernel 50cfbc83-9a03-44f5-81e3-cfc5c3d47055 died, removing from map.

**Comment by prabhakk-mw** [comment]
Hi @jonathanlilly 

This is most likely because you may have setup a password to access the Jupyter Notebook.
Could you please follow the steps listed in this answer:
https://github.com/mathworks/jupyter-matlab-proxy/issues/23#issuecomment-1525033545

Feel free to reopen this issue if the workaround mentioned above does not resolve the issue.

Thank you!

**Comment by jonathanlilly** [comment]
Hi @prabhakk-mw, 

Thank you. This worked, although the file I had to delete was  jupyter_notebook_config.json.  

It would be good to mention this in the docs because it's not very obvious.  I believe the password authentication was set up by default in a recent Jupyter upgrade, where it was the recommended option.

**Comment by prabhakk-mw** [comment]
Hi @jonathanlilly 

Thank you for confirming, and sharing your experience.
Yes, we will make a note of this in our docs, and also add an error message into the Kernel directly which hints at the required next steps.

Thank you for using the MATLAB Integration for Jupyter!

**Comment by jonathanlilly** [comment]
Wonderful.  Thank you as well!  I have been using Jupyter with Matlab for a while but this new integration makes it a lot easier :)

**Comment by jonathanlilly** [comment]
Hello, looking into this again as it has been a year.  I'm stil not able to get Matlab in Jupyter to work with password authentication, although it does work with token authentication.  

Is password authentication still not yet supported?  If so, it would be great to mention this in the installation documentation.  Currently it seems not to be mentioned in the installation documentation nor the troubleshooting.
