### ISSUE TITLE
MATLAB Kernel could not communicate with MATLAB on Windows11        

### ISSUE THREAD

**Issue by SCaAg** [mathworks/jupyter-matlab-proxy#97]
### Summary

Hi.
I am experiencing an issue similar to the one described in issue #91. I am using MATLAB R2024a on Windows 11 and have followed the instructions to install the MATLAB kernel. However, when I run Jupyter Lab and attempt to execute a MATLAB code block, I receive the following error message:
> Error: MATLAB Kernel could not communicate with MATLAB.
> Reason: Possibly due to invalid jupyter security tokens.

If I click the "Open MATLAB" button, I can access the web version of MATLAB, but I am still unable to run MATLAB code within Jupyter Lab.

I have tried this with Python 3.10 and Python 3.11 and ensured that both Jupyter Lab and the jupyter-matlab-proxy are up-to-date. 

Additionally, I have noticed some errors in the Jupyter Lab backend:
```output
[W 2024-08-30 12:46:46.972 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993206963 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:46.973 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:46:46.976 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993206963 (159c5e53404541efbd3b423a01752144@::1) 5.21ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
INFO:MATLABProxyApp:Stopped (any running) MATLAB process.
[I 2024-08-30 12:46:47.564 LabApp] Build is up to date
[W 2024-08-30 12:46:47.904 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:47.918 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (159c5e53404541efbd3b423a01752144@::1) 16.39ms referer=None
[W 2024-08-30 12:46:47.923 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993207919 (127.0.0.1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:47.924 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:46:47.924 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993207919 (159c5e53404541efbd3b423a01752144@127.0.0.1) 2.10ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
[W 2024-08-30 12:46:48.909 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:48.910 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (159c5e53404541efbd3b423a01752144@::1) 2.93ms referer=None
[W 2024-08-30 12:46:48.915 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993208911 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:48.916 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:46:48.917 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993208911 (159c5e53404541efbd3b423a01752144@::1) 1.97ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
[W 2024-08-30 12:46:53.913 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:53.914 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (159c5e53404541efbd3b423a01752144@::1) 2.00ms referer=None
[W 2024-08-30 12:46:53.917 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993213914 (127.0.0.1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:46:53.917 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:46:53.918 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993213914 (159c5e53404541efbd3b423a01752144@127.0.0.1) 1.25ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
[W 2024-08-30 12:47:04.913 ServerApp] 404 GET /api/kernels/6536b383-a8b6-44eb-be43-62d8f9287edf?1724993224904 (::1): Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf
[W 2024-08-30 12:47:04.913 ServerApp] wrote error: 'Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf)
[W 2024-08-30 12:47:04.914 ServerApp] 404 GET /api/kernels/6536b383-a8b6-44eb-be43-62d8f9287edf?1724993224904 (159c5e53404541efbd3b423a01752144@::1) 2.11ms referer=http://localhost:8888/lab/workspaces/auto-Y/tree/Untitled.ipynb
[W 2024-08-30 12:47:06.910 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:47:06.910 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (159c5e53404541efbd3b423a01752144@::1) 1.89ms referer=None
[W 2024-08-30 12:47:06.914 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993226911 (127.0.0.1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:47:06.914 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:47:06.915 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993226911 (159c5e53404541efbd3b423a01752144@127.0.0.1) 1.00ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
[W 2024-08-30 12:47:14.006 ServerApp] 404 GET /serviceregistrylookup/1/service (159c5e53404541efbd3b423a01752144@::1) 1.00ms referer=http://localhost:8888/
[W 2024-08-30 12:47:16.034 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:47:16.035 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (159c5e53404541efbd3b423a01752144@::1) 2.00ms referer=None
[W 2024-08-30 12:47:16.120 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993236061 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:47:16.120 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:47:16.121 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993236061 (159c5e53404541efbd3b423a01752144@::1) 2.04ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
[W 2024-08-30 12:47:29.922 ServerApp] 404 GET /api/kernels/6536b383-a8b6-44eb-be43-62d8f9287edf/channels?session_id=12526fb7-eebe-4854-9d86-5f5ee39a1439 (::1): Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf
[W 2024-08-30 12:47:29.923 ServerApp] 404 GET /api/kernels/6536b383-a8b6-44eb-be43-62d8f9287edf/channels?session_id=12526fb7-eebe-4854-9d86-5f5ee39a1439 (159c5e53404541efbd3b423a01752144@::1) 1.00ms referer=None
[W 2024-08-30 12:47:29.929 ServerApp] 404 GET /api/kernels/6536b383-a8b6-44eb-be43-62d8f9287edf?1724993249924 (::1): Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf
[W 2024-08-30 12:47:29.929 ServerApp] wrote error: 'Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 6536b383-a8b6-44eb-be43-62d8f9287edf)
[W 2024-08-30 12:47:29.930 ServerApp] 404 GET /api/kernels/6536b383-a8b6-44eb-be43-62d8f9287edf?1724993249924 (159c5e53404541efbd3b423a01752144@::1) 2.16ms referer=http://localhost:8888/lab/workspaces/auto-Y/tree/Untitled.ipynb
[W 2024-08-30 12:47:51.946 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:47:51.948 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805/channels?session_id=758ec3aa-82c3-4b4a-b501-e950b417b295 (159c5e53404541efbd3b423a01752144@::1) 2.00ms referer=None
[W 2024-08-30 12:47:51.983 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993271955 (::1): Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805
[W 2024-08-30 12:47:51.983 ServerApp] wrote error: 'Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805'
    Traceback (most recent call last):
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\web.py", line 1790, in _execute
        result = await result
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 506, in kernel_model
        self._check_kernel_id(kernel_id)
      File "C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 537, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: e6a246f6-0744-41e4-ac53-d59dcf4fd805)
[W 2024-08-30 12:47:51.984 ServerApp] 404 GET /api/kernels/e6a246f6-0744-41e4-ac53-d59dcf4fd805?1724993271955 (159c5e53404541efbd3b423a01752144@::1) 2.00ms referer=http://localhost:8888/lab/workspaces/auto-H/tree/Untitled1.ipynb
```

I would greatly appreciate any guidance or assistance in resolving this issue.
Thank you for your help!

### Issue found in

MATLAB Kernel

### Script output

------------------------------------------------------------------------------------------------------------------------
                                                         MATLAB
------------------------------------------------------------------------------------------------------------------------
matlab - D:\Programs\MATLAB\R2024a\bin\matlab.EXE ok

------------------------------------------------------------------------------------------------------------------------
                                                    matlab-proxy-app
------------------------------------------------------------------------------------------------------------------------
matlab-proxy-app - C:\Users\lilliu\AppData\Local\Programs\Python\Python310\Scripts\matlab-proxy-app.EXE ok

------------------------------------------------------------------------------------------------------------------------
                                                        Jupyter
------------------------------------------------------------------------------------------------------------------------
jupyter - C:\Users\lilliu\AppData\Local\Programs\Python\Python310\Scripts\jupyter.EXE ok

------------------------------------------------------------------------------------------------------------------------
                                               Python and pip executables
------------------------------------------------------------------------------------------------------------------------
python - C:\Users\lilliu\AppData\Local\Programs\Python\Python310\python.EXE ok

Python 3.10.11

pip - C:\Users\lilliu\AppData\Local\Programs\Python\Python310\Scripts\pip.EXE ok

pip 23.0.1 from C:\Users\lilliu\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)

python3 - None  X
Recommendation: python3 is not installed. Please install python3.

------------------------------------------------------------------------------------------------------------------------
                                                     OS information
------------------------------------------------------------------------------------------------------------------------
Windows
10
Windows-10-10.0.22631-SP0
uname_result(system='Windows', node='Legion', release='10', version='10.0.22631', machine='AMD64')

------------------------------------------------------------------------------------------------------------------------
                                                   Conda information
------------------------------------------------------------------------------------------------------------------------

conda - None

------------------------------------------------------------------------------------------------------------------------
                                                   Installed packages
------------------------------------------------------------------------------------------------------------------------

jupyter_client            8.6.2
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter-matlab-proxy      0.14.0
jupyter_server            2.14.2
jupyter_server_proxy      4.4.0
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
matlab-proxy              0.19.0
notebook_shim             0.2.4[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

------------------------------------------------------------------------------------------------------------------------
                                               Jupyter server extensions
------------------------------------------------------------------------------------------------------------------------

Config dir: C:\Users\lilliu\.jupyter

Config dir: C:\Users\lilliu\AppData\Local\Programs\Python\Python310\etc\jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 2.2.5 ok
    jupyter_server_proxy enabled
    - Validating jupyter_server_proxy...
      jupyter_server_proxy 4.4.0 ok
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
      jupyter_server_terminals 0.5.3 ok
    jupyterlab enabled
    - Validating jupyterlab...
Extension package jupyterlab took 0.1161s to import
      jupyterlab 4.2.5 ok
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  ok

Config dir: C:\ProgramData\jupyter

JupyterLab v4.2.5
C:\Users\lilliu\AppData\Local\Programs\Python\Python310\share\jupyter\labextensions
        jupyterlab_pygments v0.3.0 enabled ok (python, jupyterlab_pygments)
        jupyter_matlab_labextension v1.0.0 enabled ok (python, jupyter_matlab_labextension)
        @jupyterhub/jupyter-server-proxy v4.4.0 enabled ok

------------------------------------------------------------------------------------------------------------------------
                                                 Environment variables
------------------------------------------------------------------------------------------------------------------------

**Comment by rashedmyt** [comment]
Hi @SCaAg

Thank you for using MATLAB Integration for Jupyter.

From the description of the issue, it seems like the kernel is not able to communicate with MATLAB through Jupyter. Can you please provide the following information for further investigation.
1. Are you using an empty password for the Jupyter server? Password enabled jupyter servers are currently not supported by this integration. We are actively working towards removing this limitation.
2. Following [this guide](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/troubleshooting/troubleshooting.md#enable-logging), please enable debug logging and reproduce the issue. Then provide the logs printed in the terminal after starting Jupyter server here. Also, provide the output of `jupyter server list --json` when the Jupyter server in running.

**Comment by SCaAg** [comment]
Hi @rashedmyt 

Thank you for your response and assistance.

I have identified the cause of the issue. It was due to a command-line proxy setting on my local machine, which was interfering with the communication between the MATLAB Kernel and MATLAB.

After adjusting the proxy settings, everything is working correctly now.

Thank you again for your support!
